### PR TITLE
Add new example workflow

### PR DESCRIPTION
**Pull request by simonbray**
I'd like to add a new example workflow for the WIP planemo tutorial here: https://github.com/galaxyproject/planemo/pull/1102 - I hope that's okay? This one contains only tools which are installed by default on Galaxy instances and also has an example of an input param as well as input datasets.

### CODE REVIEW

**Comment by bgruening** [comment]
This also needs your Galaxy PR merged first?

**Review by hexylena — APPROVED** [review]

**Comment by simonbray** [comment]
> This also needs your Galaxy PR merged first?

No, it doesn't - I think you are only running `planemo test` on the workflows, correct? My PR only affects `planemo run`.

**Comment by bgruening** [comment]
Very nice! Thanks!

**Comment by simonbray** [comment]
Cool. Thanks for the merge! :)

**Pull request merged**
