### PR TITLE
workflow testing for dip

### PR DESCRIPTION
**Pull request by polkhe**
- workflow
- test.yml

### CODE REVIEW

**Comment by erasche** [comment]
Hi @polkhe could you reformat the workflow? Using something like `cat workflow | jq -S . > out.ga` on the command line, or I think there are webservices. If you reformat with sorted keys it is best so we can keep the diffs readable for any future changes.

**Comment by polkhe** [comment]
Hi @erasche sure, done

**Comment by erasche** [comment]
Looks great, thanks so much!

**Comment by bgruening** [comment]
Super cool, I added the batch: https://github.com/usegalaxy-eu/workflow-testing/commit/e8b036e0751af414b5b3835bdb21c4b8bf03e47f

ping @wm75 ... I see gemini here.

**Comment by wm75** [comment]
@bgruening yes, just don't conclude that it's the patched version

**Pull request merged**
