### PR TITLE
Try to fix ref-based wf test

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by bgruening** [comment]
Gracias! I will update Jenkins now ...

**Comment by bgruening** [comment]
@bebatut was this working for you locally? I added two commits to it, but it is still failing for jenkins: https://build.galaxyproject.eu/job/usegalaxy-eu/job/workflow-testing/53/PYTHON=System-CPython-2.7,WORKFLOW=training%2Ftranscriptomics%2Fref-based%2Fref_based.ga/consoleText

The wired thing is that I do not get a meaningful error message. I will try again, but if you have any idea let me know.

**Comment by bebatut** [comment]
I am still testing it locally

**Comment by bgruening** [comment]
Fixed it in: https://github.com/usegalaxy-eu/workflow-testing/commit/42f2690bb301aedd83cc9c96b4eda7b96476f02f it strange that Jenkins is not showing the error report.

We are down to 3 failing tests ... the general-assembly one is a real Galaxy error with a missing tool. Super cool!

**Pull request merged**
